#!/bin/bash

# start docker and emacs
docker run \
      -d \
      -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
      -v $XAUTHORITY:/developer/.Xauthority \
      -v ${PWD}/project:/project \
      -e DISPLAY=unix${DISPLAY} \
      --device /dev/snd \
      --name docker-emacs \
      cmiles74/docker-emacs-js-clojure

docker exec docker-emacs /developer/bin/start-terminal

